#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

cd /var/www/html

composer install
php artisan migrate 
# php artisan db:seed 
php artisan serve --host=0.0.0.0 --port=8080