version: "3"
services:
    mysql:
        container_name: laravel_mysql
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        tty: true
        restart: unless-stopped
        networks:
            - web
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/entrypoints:/docker-entrypoint-initdb.d

    app:
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - web
        ports:
            - "8080:8080"
        environment:
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - "./:/var/www/html"
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ""
        depends_on:
            - mysql
        networks:
            - web

networks:
    web:
        external: true
